name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1: Set up Node.js and Java
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 2: Install Node.js dependencies for React app
      - name: Install Node.js dependencies
        run: |
          cd src/main/client/pcShop
          npm ci

      # Step 3: Build React app
      - name: Build React app
        run: |
          cd src/main/client/pcShop
          npm run build

      # Step 4: Ensure the Spring Boot static resources directory exists
      - name: Ensure static resources directory exists
        run: |
          if [ ! -d "src/main/resources/static" ]; then
            mkdir -p src/main/resources/static
            echo "Created static resources directory."
          else
            echo "Static folder already exists."
          fi

      # Step 5: Move React build output to Spring Boot static resources
      - name: Move React build to static resources
        run: |
          cp -r src/main/client/pcShop/dist/* src/main/resources/static/

      # Step 6: Set execute permissions for gradlew
      - name: Set execute permissions for gradlew
        run: |
          chmod +x ./gradlew

      # Step 7: Clean and build the Spring Boot project using Gradle
      - name: Build Spring Boot project
        run: |
          ./gradlew clean build

      # Step 8: Archive the build artifact (JAR file) for download
      - name: Archive JAR file
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-artifact
          path: build/libs/*.jar

  test:
    runs-on: ubuntu-latest
    needs: build  # Ensures the test job runs after the build job completes
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432  # Ensure PostgreSQL runs on its default port
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Set up Java and Node.js for testing (optional)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Install Node.js dependencies
      - name: Install Node.js dependencies
        run: |
          cd src/main/client/pcShop
          npm ci
